export const products=[
  {
    id: "1",
    image: "/images/jacket-vintage.jpg",
    fallbackImage: "/images/fallback-jacket.jpg",
    alt: "Vintage Denim Jacket",
    title: "Vintage Denim Jacket",
    price: "$45.00",
    originalPrice: "$65.00",
    rating: 4.8,
    reviewCount: 86,
    isNew: false,
    isSale: true,
  },
  {
    id: "2",
    image: "/images/sneakers-white.webp",
    fallbackImage: "/images/fallback-sneakers.jpg",
    alt: "Retro White Sneakers",
    title: "Retro White Sneakers",
    price: "$60.00",
    originalPrice: "$90.00",
    rating: 4.6,
    reviewCount: 112,
    isNew: true,
    isSale: true,
  },
  {
    id: "3",
    image: "/images/handbag-leather.webp",
    fallbackImage: "/images/fallback-handbag.jpg",
    alt: "Brown Leather Handbag",
    title: "Genuine Leather Handbag",
    price: "$80.00",
    originalPrice: "$110.00",
    rating: 4.9,
    reviewCount: 145,
    isNew: true,
    isSale: false,
  },
  {
    id: "4",
    image: "/images/flannel-shirt.jpg",
    fallbackImage: "/images/fallback-flannel.jpg",
    alt: "Plaid Flannel Shirt",
    title: "Plaid Flannel Shirt",
    price: "$25.00",
    originalPrice: "$35.00",
    rating: 4.4,
    reviewCount: 72,
    isNew: false,
    isSale: true,
  }
]